site_name: Kernel Glossary
theme:
  name: material
plugins:
  - search
  - tags

nav:
  - Tags: TAGS.md
  - Development Process:
    - The kernel community:
      - Overview: workflows/development-process.md
      - Release model: workflows/kernel-release-model.md
      - Stable releases: workflows/stable-releases.md
      - Coding patterns: workflows/kernel-coding-patterns.md
      - Upstreaming process: workflows/upstreaming-process.md
  - Tooling:
    - Git:
      - git basics: workflows/git-basics.md
      - git interrogators: workflows/git-interrogators.md
      - git bisect: workflows/git-bisect.md
      - git worktree: workflows/git-worktree.md
      - git rebase (interactive): workflows/git-rebase-interactive.md
      - git rebase: workflows/git-rebase.md
    - Finding patches:
      - Xapian Query Syntax: workflows/xapian-query-syntax.md
      - lei: workflows/lei.md
    - Applying patches:
      - git cherry-pick: workflows/git-cherry-pick.md
      - Backporting: workflows/backporting.md
      - Applying .mbox and .patch: workflows/applying-patches.md
    - Sending patches:
      - git send-email: workflows/git-send-email.md
      - b4: workflows/b4.md
      - patman: workflows/patman.md
    - Building the kernel:
      - Kconfig: workflows/kconfig.md
      - Kbuild: workflows/kbuild.md
      - Kernel compilation (native): workflows/compiling-kernel-native.md
      - Kernel compilation (cross): workflows/compiling-kernel-cross.md
      - Kernel binaries: workflows/kernel-binaries.md
  - Debugging:
    - Overview:
      - Debugging overview: debugging/debugging-overview.md
    - Print debugging:
      - Dynamic debug: debugging/dynamic-debug.md
      - debugfs: debugging/debugfs.md
    - Call traces:
      - Analyze call traces: debugging/call-trace-analysis.md
      - decode_stacktrace.sh: debugging/decode_stacktrace.md
      - pstore: debugging/pstore.md
    - Postmoterm:
      - kdump:  debugging/kdump.md
      - drgn: debugging/drgn.md
      - kgdb: debugging/kgdb.md
    - Kernel tracing:
      - Tracing overview: debugging/tracing-overview.md
      - ftrace (trace-cmd): debugging/trace-cmd.md
      - ftrace (tracefs): debugging/tracefs.md
      - bpftrace: debugging/bpftrace.md
      - Event sources: debugging/event-sources.md
      - Tracepoints: debugging/tracepoints.md
      - Kprobes: debugging/kprobe.md
    - Sanitizers:
      - Overview: debugging/sanitizer-overview.md
      - KASAN: debugging/kasan.md
      - KMEMLEAD: debugging/kmemleak.md
      - KFENCE: debugging/kfence.md
      - KCSAN: debugging/kcsan.md
      - UBSAN:  debugging/ubsan.md
      - Lockdep: debugging/lockdep.md
    - Static checks:
      - SPARSE: debugging/sparse.md
      - smatch: debugging/smatch.md
      - coccinelle: debugging/coccinelle.md
  - Concurrency:
    - Sources of concurrency:
      - IRQ: concurrency/irq.md
      - softirq: concurrency/softirq.md
      - preemption: concurrency/preemption.md
    - Work deferring:
      - Workqueue: concurrency/workqueue.md
      - tasklet: concurrency/tasklet.md
      - Threaded IRQ: concurrency/threaded-irq.md
    - Locking:
      - spinlock: concurrency/spinlock.md
      - mutex: concurrency/mutex.md
      - semaphore: concurrency/semaphore.md
      - RCU: concurrency/rcu.md
    - Schedulers:
      - Overview: concurrency/scheduler-overview.md
      - Processes: concurrency/processes.md
      - fair_sched: concurrency/fair_sched.md
      - rt_sched: concurrency/rt_sched.md
      - dl_sched: concurrency/dl_sched.md
    - Memory model:
      - Compiler barriers: concurrency/compiler-barriers.md
      - CPU barriers: concurrency/cpu-barriers.md
      - Memory model: concurrency/memory-model.md
    - System calls:
      - System call: concurrency/system-calls.md
      - vDSO: concurrency/vdso.md
      - strace: concurrency/strace.md
    - Time:
      - Timer and timekeeping: concurrency/time.md
      - hrtimer: concurrency/hrtimer.md
  - Drivers:
    - Overview:
      - Kernel modules: drivers/kernel-modules.md
      - Driver model: drivers/driver-model.md
      - udev: drivers/udev.md
    - Hardware Descriptions:
      - Device tree: drivers/device-tree.md
      - ACPI: drivers/acpi.md
    - Buses (non-numerable):
      - I2C: drivers/i2c.md
      - SPI: drivers/spi.md
      - Platform: drivers/platform-bus.md
    - Buses (enumerable):
      - USB: drivers/usb.md
      - PCIe: drivers/pci.md
    - Hardware Resources:
      - GPIO: drivers/gpio.md
      - Interrupts: drivers/interrupts.md
      - pinctrl: drivers/pinctrl.md
      - Clocks: drivers/clocks.md
      - regmap: drivers/regmap.md
      - DMA: drivers/dma.md
      - firmware: drivers/firmware.md
    - Other topics:
      - DT schema: drivers/dt-schema.md
      - device_link: drivers/device_link.md
  - Power Management:
    - Overview:
      - PM Frameworks: pm/pm-overview.md
    - System-wide suspend:
      - System-wide suspend: pm/system-wide-suspend.md
      - Suspend-to-idle: pm/s2idle-freeze.md
      - Standby: pm/standby.md
      - Suspend-to-ram: pm/s2ram-deep.md
    - Other System-wide suspend topics:
      - Modern Standby (S0ix): pm/s0ix.md
      - ACPI S-States: pm/acpi-s-states.md
    - Device Runtime Power Management:
      - Runtime PM: pm/runtime-pm.md
      - PM Domain (genpd): pm/pm-domain.md
    - CPU Runtime Power Management:
      - cpufreq: pm/cpufreq.md
      - OPP: pm/opp.md
      - ACPI P-States: pm/acpi-p-states.md
    - PM QoS:
      - PM QoS: pm/qos.md
    - CPU Idle:
      - cpuidle: pm/cpuidle.md
      - ACPI C-States: pm/acpi-c-states.md
    - Thermal Management:
      - Thermal subsystem: pm/thermal.md
      - thermald: pm/thermald.md
